env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
before:
  hooks:
    - go mod download
builds:
- env:
  goos:
    - darwin
  goarch:
    - amd64
    - arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
  binary: md2pikchrs
  flags:
    - -trimpath
  main: ./cmd/md2pikchrs/main.go
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
release:
  github:
      owner: gebv
      name: pikchr
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      amd64: x86_64
    files:
      - README.md
      - cmd/md2pikchrs/README.md
      - LICENSE
      - completions/*

brews:
  - name: md2pikchrs
    folder: Formula
    tap:
      owner: gebv
      name: homebrew-tap
    homepage:  https://github.com/gebv/pikchr
    description: cli tools to integrate into your development process for generate pikchrs diagrams
    license: MIT
    test: |
      system "#{bin}/md2pikchrs -v"
